Completed first version of document ingestion API
g-fiorina/onboarding-documents-api pull request #4
Opened 2024-08-02 14:54 UTC by g-fiorina

This pull request includes the implementation of the document ingestion API using FastAPI. It is designed to receive a PDF link, convert the PDF to Markdown using llmsherpa, and store the PDF title and Markdown content in a PostgreSQL database.

Organized the project into modules: document_processor.py, database.py, and api.py.
Stored configuration details, including database settings and llmsherpa API URL, in config/config.json and config/secrets.json.
Document Processor (document_processor.py): Functions to download PDFs, convert to Markdown, and extract titles. Clean-up of temporary files after processing.
API Endpoints (api.py): Endpoint to ingest PDF links and return the extracted title. Stored processed documents in the database and returned only the title to minimize data transfer.
Database Setup (database.py): Defined the Document model with constraints. Initialized the database and created necessary tables.

2024-08-02 14:58 UTC, fede-bello commented on config/config.json
> +}
I think all this should be secret

2024-08-02 15:16 UTC, jpbalarini commented on config/config.json
> +}
Yep, let's use ENV vars for this. 
https://pypi.org/project/python-dotenv/

2024-08-02 15:38 UTC, fede-bello requested changes
Really god job in general Guille!I left some general comments

2024-08-02 15:38 UTC, fede-bello commented on README.md
> +```
I like the approach of using a `config/secrets.json`. We usually use a [`.env` file:](https://dev.to/jakewitcher/using-env-files-for-environment-variables-in-python-applications-55a1).

Then, you can load the variables doing:
```
from dotenv import load_dotenv
load_dotenv(override=True)
```
(check what the override does).
We usually also add a `.env.example` with the names of the variables we are using, in this case the file would have:
```
DATABASE_NAME = "XXX"
DATABASE_USER = "XXX"
DATABASE_HOST = "XXX"
```
etc. 
Some env variables might be public. For example, maybe you want to make the model you are using (let's say gpt-4o) public but you want to add it as a .env to easily change it depending on the project. In that case you can add the name of that to the `.env.example`.

As a last comment, let's improve the README. Maybe you can add how the project is structured and a basic tutorial on how to run it

2024-08-02 15:38 UTC, fede-bello commented on requirements.txt
Are we using this many dependencies?

2024-08-02 15:38 UTC, fede-bello commented on src/api.py
> +    yield
When is the database closed?

2024-08-02 15:38 UTC, fede-bello commented on src/api.py
> +        return ProcessedDocument(title=document.title, markdown=document.content)
Good use of Pydantic models. This does return a json like:
```
"title": <title>,
"markdown": <markdown>
```
right?
I feel like always returning all the markdown might be a too much, imagine the case where the document is extremely large. 

What do you thinkg about just returning the `id` and adding a get method that receives the id and returns the text?

2024-08-02 15:38 UTC, fede-bello commented on src/database.py
> +    db.create_tables([Document])
What happens when the table already exists?

2024-08-02 15:38 UTC, fede-bello commented on src/database.py
> +        table_name = "documents"
`Document`

2024-08-02 15:38 UTC, fede-bello commented on src/database.py
> +)
Let's change all this to use a `.env`

2024-08-02 15:38 UTC, fede-bello commented on src/document_processor.py
> +    return title
Nice! How does this work? Fine?

2024-08-02 15:38 UTC, fede-bello commented on src/document_processor.py
> +    return title, markdown_text
The llmsherpa api can also receive an url . This way you don't need to download it and then delete it.

If for some reason you want to still download it, you can send the downloaded file in the `contents`of the `.read_pdf`. Something like this:
```
def pdf_to_md(url):
    document_content = requests.get(url, timeout=100).content
    # When sending 'contents', the path_or_url parameter is ignored, but it's still required.
    doc = pdf_reader.read_pdf(path_or_url="/", contents=document_content)
    markdown = doc.to_markdown()
```

This way, you avoid the `os.remove`

2024-08-02 15:38 UTC, fede-bello commented on src/document_processor.py
> +    return title, markdown_text
(I believe that the first approach of sending an url is the best one)

2024-08-02 15:47 UTC, fede-bello commented on src/database.py
> +class Document(Model):
Let's add an `id` as a primary field. 
It might be useful to also save the the url

2024-08-02 16:38 UTC, fede-bello commented on src/database.py
> +        table_name = "documents"
(https://stackoverflow.com/questions/338156/table-naming-dilemma-singular-vs-plural-names)

2024-08-02 17:59 UTC, g-fiorina commented on requirements.txt
When I created the virtual environment ingest-document-api-env for the first time I only installed using pip the following packages: fastapi, llmsherpa, peewee, psycopg2 and pymupdf. 

Then, I used the command "pip freeze > requirements.txt" to automatically generate a requirements.txt file that contains all the installed packages in my current Python environment. 
I believe this file ended up like this due to the installation of dependencies and sub-dependencies required by the main packages I installed. 

I tried leaving only the following lines in a new virtual environment:
fastapi==0.111.1
llmsherpa==0.1.4
peewee==3.17.6
psycopg2==2.9.9
PyMuPDF==1.24.9
requests==2.32.3

With them the application works just fine, but if I use the command "pip freeze > requirements.txt" the requirements.txt file fills up again. 

What do you think I should do, leave all the lines and be more clear or keep only the main packages needed and let the dependencies and sub-dependencies be installed in the background?

2024-08-02 18:57 UTC, fede-bello commented on requirements.txt
If that's the case its perfect like it is now :)

2024-08-02 22:32 UTC, g-fiorina commented on src/database.py
> +        table_name = "documents"
I will change it.
Very clear, thank you!

2024-08-02 22:40 UTC, g-fiorina commented on src/database.py
> +    db.create_tables([Document])
According to Peewee documentation: "By default, Peewee includes an IF NOT EXISTS clause when creating tables. If you want to disable this, specify safe=False." 

So, if the table does exist, it will not raise any error or re-create the table, just not execute the CREATE table query.

2024-08-05 12:45 UTC, g-fiorina commented on src/database.py
> +class Document(Model):
It is already included when saved in the database. According to peewee documentation: "[...] because none of the fields are initialized with primary_key=True, an auto-incrementing primary key will automatically be created and named “id”. "

I saved the url and also it now returns the id when saved and the api has a get method to return a document by the id.

2024-08-05 12:54 UTC, g-fiorina commented on src/api.py
> +        return ProcessedDocument(title=document.title, markdown=document.content)
Completely agree. It now returns the id and the title of the pdf. 
Done!

2024-08-05 15:21 UTC, g-fiorina commented on src/api.py
> +    yield
I changed the code to use context managers. Now it will open a connection and close a connection only when it is needed (to insert the document in the db, to get the document and to create the table when the API starts up).

2024-08-05 16:48 UTC, g-fiorina commented on src/document_processor.py
> +    return title
I tested it with 5 different files and it works fine!

2024-08-05 17:03 UTC, fede-bello approved these changes
Really god job Guille!

2024-08-05 17:22 UTC, merged