Add search endpoint for document chunks by text similarity
g-fiorina/onboarding-documents-api pull request #9
Opened 2024-08-22 20:38 UTC by g-fiorina

- Implemented a new /search GET endpoint in api.py that allows users to search for document chunks similar to a given text.
- Added get_similar_chunks function to handle the similarity search using OpenAI embeddings.
- Included error handling for invalid inputs and unexpected errors.

2024-08-23 15:16 UTC, fede-bello requested changes
I really liked the approach Guille, I left some comments

2024-08-23 15:16 UTC, fede-bello commented on ingest_documents_api/api.py
> +    text: str, minimum_similarity: float = -0.8, max_quantity_chunks: int = None
What do you think about making this a constant to improve readability? 
Also, I think the value might be a little bit to high, I would test this a bit more

2024-08-23 15:16 UTC, fede-bello commented on ingest_documents_api/database.py
> +            DocumentChunk.document_id.alias("document_id"),
Why is the alias needed?

2024-08-23 15:16 UTC, fede-bello commented on ingest_documents_api/database.py
> +            DocumentChunk.embedding.max_inner_product(embedded_text).alias(
What do you thinkg about defining a `similarity = DocumentChunk.embedding.max_inner_product(embedded_text) ` and using that in the select, where and order by?

2024-08-23 15:16 UTC, fede-bello commented on ingest_documents_api/database.py
> +    if max_quantity_chunks:
I think its better to always define a limit and if the parameter is sent to override that limite.
Without a limit you ran the risk of running out of memory, taking too long in the query or eventually passing way to much context to the LLM

2024-08-23 15:20 UTC, g-fiorina commented on ingest_documents_api/database.py
> +            DocumentChunk.document_id.alias("document_id"),
It is a mistake, I left it while doing some changes and never removed it. I will erase it, thank you!

2024-08-23 15:31 UTC, g-fiorina commented on ingest_documents_api/database.py
> +            DocumentChunk.embedding.max_inner_product(embedded_text).alias(
Amazing, much clearer!

2024-08-26 13:59 UTC, fede-bello approved these changes
Nice

2024-08-26 14:10 UTC, merged